version: "3.6"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nba-app-client
    image: nba_app
    environment:
      - NODE_ENV=development
      - REACT_APP_SERVER_HOST=http://localhost:3000
    ports:
      - 3000:3000
    volumes:
      - "./:/app"
volumes:
  ? data

  # docker run -d --name nba-app-server -p 80:80 -v `pwd`/data/db.json:/data/db.json clue/json-server