version: "3.6"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    container_name: Client
    image: nba_app
    environment:
      - NODE_ENV=development
      - REACT_APP_SERVER_HOST=http://localhost:3000
    ports:
      - 3001:3000
    volumes:
      - "./:/app"
      - "/app/node_modules"
    
  json-server:
    image: williamyeh/json-server
    command: -H localhost -p 3004 -w db.json
    ports:
      - "3004:3004"
    volumes:
      - "./:/app"
      - ./data:/data

volumes:
  ? data